version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"
    groups:
      eslint:
        patterns:
          - "eslint"
          - "eslint-plugin-jest"
          - "@typescript-eslint/parser"
          - "@typescript-eslint/eslint-plugin"
