name: 'setup-hk'
description: 'An action that can set up a modded installation of Hollow Knight for building mods in a workflow'
author: 'BadMagic100'
inputs:
  apiPath:
    required: true
    description: 'The path where modding API will be installed'
  dependencyFilePath:
    required: false
    description: 'The path to a ModDependencies.txt file that specifies mods to be installed from modlinks'
runs:
  using: 'node20'
  main: 'dist/index.js'
