name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: |
          npm install
      - run: |
          npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [windows, macos, ubuntu]
    steps:
      - uses: actions/checkout@v5
      - name: Test with no deps
        uses: ./
        with:
          apiPath: API/
      - name: Cleanup
        uses: JesseTG/rm@v1.0.3
        with:
          path: API
      - name: Test with deps
        uses: ./
        with:
          apiPath: API/
          dependencyFilePath: .github/workflows/workflow-inputs/ModDependencies.txt
